//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodeSalesProgram
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokHareket
    {
        public int Id { get; set; }
        public string Barkod { get; set; }
        public string UrunAd { get; set; }
        public string Birim { get; set; }
        public Nullable<double> Miktar { get; set; }
        public string UrunGrup { get; set; }
        public string Kullanici { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
